# Generated by Django 5.0.1 on 2024-01-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_discountcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
